Controllers/LearningController.cs
using eLearning.Interfaces;
using eLearning.Models;
using eLearning.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using eLearning.Services;

namespace eLearning.Controllers
{
    public class LearningController : Controller
    {
        // instanciranje servisa (svih funkcija koje su navedene u IKorisnikServices i implementirane u KorisnikServices) za kontrolu korisnika
        private readonly IKorisnikServices _korisnikServices;

        public LearningController(IKorisnikServices korisnikServices)
        {
            _korisnikServices = korisnikServices;
        }

        // Pocetna stranica
        public IActionResult Index()
        {
            return View();
        }
        // Profil stranica
        [HttpGet]
        public IActionResult Profile()
        {
            if (User.Identity.IsAuthenticated)
            {
                string Id = HttpContext.User.Claims.First(c => c.Type == "KorisnikID").Value;
                Korisnik korisnik = _korisnikServices.FindUserById(Id);
                ViewBag.korisnik = korisnik;

                return View();
            }
            return RedirectToAction("Index");
        }
        // Promena password-a na profil stranici
        [HttpPost]
        public IActionResult ChangePassword(KorisnikProfileViewModel korisnik)
        {
            if (User.Identity.IsAuthenticated)
            {
                string Id = HttpContext.User.Claims.First(c => c.Type == "KorisnikID").Value;
                Korisnik k = new()
                {
                    password = Security.Hash256(korisnik.password),
                };
                _korisnikServices.UpdateUserPassword(Id, k);
                Logout();
            }
            return RedirectToAction("Profile");
        }

        // Login stranica
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult Login(KorisnikLoginViewModel korisnikVM)
        {
            if (!ModelState.IsValid)
                return View(korisnikVM);

            Korisnik korisnik = _korisnikServices.Find(korisnikVM.korisnickoIme);

            if (korisnik == null || korisnik.password != Security.Hash256(korisnikVM.password))
            {
                // poruka o neuspesnoj prijavi
                ModelState.AddModelError(string.Empty, "Invalid login attempt");
                return View(korisnikVM);
            }

            string role = "Korisnik";
            if (korisnik.tip == 2)
                role = "Admin";

            List<Claim> userClaims = new()
            {
                new Claim("KorisnikID", korisnik.userID),
                new Claim("username", korisnik.korisnickoIme),
                new Claim("email", korisnik.email),
                new Claim(ClaimTypes.Role, role),
            };

            var userIdentity = new ClaimsIdentity(userClaims, "User Identity");
            var userPrincipal = new ClaimsPrincipal(new[] { userIdentity });

            HttpContext.SignInAsync(userPrincipal, new AuthenticationProperties
            {
                IsPersistent = korisnikVM.remember,
                ExpiresUtc = DateTime.Now.AddHours(1)
            });

            // dodavanje auth cookie
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult Register(KorisnikRegViewModel korisnikVM)
        {
            if (!ModelState.IsValid)
                return View(korisnikVM);

            // provera da li je korisnik vec registrovan
            Korisnik stariKorisnik = _korisnikServices.Find(korisnikVM.korisnickoIme);
            if (stariKorisnik != null)
            {
                ModelState.AddModelError(string.Empty, $"Username \"{korisnikVM.korisnickoIme}\" is already taken.");
                return View();
            }

            Korisnik k = new()
            {
                korisnickoIme = korisnikVM.korisnickoIme,
                email = korisnikVM.email,
                password = Security.Hash256(korisnikVM.password),
                tip = 1
            };
            _korisnikServices.Insert(k);
            return RedirectToAction("Index");
        }
    }
}

Controllers/ProgramController.cs
using eLearning.Interfaces;
using eLearning.Models;
using eLearning.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eLearning.Controllers
{
    public class ProgramController : Controller
    {
        private readonly IProgramServices _programServices;
        private readonly IKurseviServices _kurseviServices;
        private readonly IKategorijeServices _kategorijeServices;
        private readonly ISchoolServices _schoolServices;

        public ProgramController(
            IProgramServices programServices,
            IKurseviServices kurseviServices,
            IKategorijeServices kategorijeServices,
            ISchoolServices schoolServices)
        {
            _programServices = programServices;
            _kurseviServices = kurseviServices;
            _kategorijeServices = kategorijeServices;
            _schoolServices = schoolServices;
        }

        public IActionResult Index()
        {
            // ucitavanje podataka iz baze
            List<SekcijaPrograma> sekcije = _programServices.Read();
            // sortiranje sekcija prema broju
            sekcije = sekcije.OrderBy(s => s.Broj).ToList();

            // Generisanje liste sekcija za prikaz korisniku
            List<SekcijaViewModel> ListaSekcija = new();

            foreach (SekcijaPrograma sekcija in sekcije)
            {
                // lista za smestanje kurseva koji se nalaze u sekciji
                List<KursSekcijeViewModel> kurseviVM = new();

                // sortiranje kurseva prema broju
                sekcija.Kursevi = sekcija.Kursevi.OrderBy(k => k.Broj).ToList();

                // Prolazak kroz niz ID kurseva
                foreach (var k in sekcija.Kursevi)
                {
                    // trazenje kursa prema ID
                    Kursevi dbKurs = _kurseviServices.Find(k.KursID);

                    // popunjavanje liste sa kursevima
                    if (dbKurs != null)
                    {
                        kurseviVM.Add(new KursSekcijeViewModel
                        {
                            Naziv = dbKurs.imekursa,
                            Nivo = _kurseviServices.getLevel(dbKurs.nivoKursa), 
                            NivoID = dbKurs.nivoKursa,
                            Broj = k.Broj,
                            Kategorija = _kategorijeServices.Find(dbKurs.kategorijaID).imekategorije,
                            Skola = _schoolServices.Find(dbKurs.skolaID).naziv,
                            Link = dbKurs.kursID
                        });
                        kurseviVM = kurseviVM.OrderBy(k => k.NivoID).ThenBy(k => k.Broj).ToList();
                    }
                }

                // popunjavanje liste sa sekcijama
                ListaSekcija.Add(new SekcijaViewModel
                {
                    Opis = sekcija.Opis,
                    Kursevi = kurseviVM
                });
            }

            return View(ListaSekcija);
        }

/*        //insert
          _programServices.Insert(new SekcijaPrograma
            {
                Opis = "Opis prve sekcije",
                Broj = 1,
                Kursevi = new List<KurseviSekcije>()
                {
                    new KurseviSekcije { KursID = "60a6ab7ee72d52bfeea8ce0d", Broj = 1 }
}
            });*/
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="/js/jquery-3.6.0.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("skripte", required: false)
    <script src="/js/jquery-3.6.0.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/css/main.css">
    @RenderSection("skripte", required: false)
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    @*<link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css" />*@

    <script src="/js/jquery-3.6.0.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"></script>
    <script src="//ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="main_container">
        <nav class="main-nav">
            <div class="logo">
                <a asp-controller="Learning" asp-action="Index"><span>e</span>Learning</a>
            </div>
            <div class="right">
                @if (User.Identity.IsAuthenticated)
                {
                <div class="right_wrap">
                    <div class="profile_desc"><span class="wlc">Welcome</span> @User.Claims.First(c => c.Type == "username").Value</div>
                    <img class="profile_picture" src="~/images/Sajt-slike/profile.png" />
                    <ul class="profile_nav">
                        <li><a asp-controller="Learning" asp-action="Profile">Profile</a></li>
                        <li><a asp-controller="Program" asp-action="Index">Program</a></li>
                        <li><a asp-controller="Learning" asp-action="Logout">Logout</a></li>
                    </ul>
                </div>
                }
                else
                {
                <div class="button_wrap">
                    <div class="btn"><a asp-controller="Learning" asp-action="Login">Login</a></div>
                    <div class="btn btn-white"><a asp-controller="Learning" asp-action="Register">Register</a></div>
                </div>
                }
            </div>
        </nav>
        <div class="content">
            @RenderBody()
        </div>
    </div>
    <script src="~/js/schools.js"></script>
</body>
</html>