Controllers/KurseviController.cs
using eLearning.Interfaces;
using eLearning.Models;
using eLearning.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MongoDB.Driver;
using Microsoft.AspNetCore.Authorization;

namespace eLearning.Controllers
{
    [Authorize]
    public class KurseviController : Controller
    {

        // instanciranje servisa (svih funkcija koje su navedene u IKorisnikServices i implementirane u KorisnikServices) za kontrolu korisnika
        private readonly IKurseviServices _kurseviServices;
        private readonly IKategorijeServices _kategorijeServices;
        private readonly ISchoolServices _schoolServices;
        // 
        public KurseviController(IKurseviServices kurseviServices, IKategorijeServices kategorijeServices, ISchoolServices schoolServices)
        {
            _kurseviServices = kurseviServices;
            _kategorijeServices = kategorijeServices;
            _schoolServices = schoolServices;
        }

        public IActionResult CourseMap()
        {
            return View();
        }

        // GET: KurseviController

        [HttpGet("/courses/{naziv?}")]
        public IActionResult Courses(string naziv, string search, int? level, int? page, string schoolID)
        {
            // search
            ViewBag.search = search;
            ViewBag.level = level;

            if (schoolID != null)
                ViewBag.school = _schoolServices.Find(schoolID);
            else
                ViewBag.school = null;

            List<Kursevi> listKurseva;
            List<Kategorije> listKategorija;

            string kategorijaID = null;
            if (naziv != null)
            {
                var kategorija = _kategorijeServices.FindByName(naziv);
                if (kategorija == null) return NotFound();
                kategorijaID = kategorija.kategorijaID;
            }

            if (page == null)
            {
                page = 1;
            }
            int pageSize = 9;
            ViewBag.page = page;

            if (level == null)
                level = 0; // svi nivoi

            int courseCount;
            (listKurseva, courseCount) = _kurseviServices.GetCourses(kategorijaID, search, (int)level, (int)page, pageSize, schoolID);


            double maxPages = (double)courseCount / pageSize;
            ViewBag.maxPages = (int)Math.Ceiling(maxPages);
            ViewBag.total = courseCount;

            listKategorija = _kategorijeServices.Read();

          
            var kursevi = new List<DetailsForCourseViewModel>();
            foreach (var item in listKurseva)
            {
                // skracivanje opisa kursa
                if (item.detaljikursa.Length > 50)
                    item.detaljikursa = item.detaljikursa.Substring(0, 50) + "...";
                if (item.imekursa.Length > 46)
                    item.imekursa = item.imekursa.Substring(0, 44) + "...";

                kursevi.Add(new DetailsForCourseViewModel()
                {
                    kurs = item,
                    nivo = _kurseviServices.getLevel(item.nivoKursa)
                });
            }
            var viewmodel = new KursKategorijaViewModel
            {
                kategorijes = listKategorija,
                kursevis = kursevi,
            };
            ViewBag.kursevi = kursevi;
            return View(viewmodel);
        }
          

        [HttpGet]
        public ActionResult<Kursevi> CourseDetails(string id) {
            var findKurs = _kurseviServices.Find(id);
            var level = _kurseviServices.getLevel(findKurs.nivoKursa);

            // provera da li skola postoji
            string schoolName;
            if (findKurs.kategorijaID == null)
            {
                schoolName = "Uncategorized";
            }
            else
            {
                var s = _schoolServices.Find(findKurs.skolaID);
                if (s == null)
                    schoolName = "Uncategorized";
                else
                    schoolName = s.naziv;
            }

            // provere ako kategorija ne postoji
            string categoryName;
            if (findKurs.kategorijaID == null)
            {
                categoryName = "Uncategorized";
            }
            else
            {
                var category = _kategorijeServices.Find(findKurs.kategorijaID);
                if (category == null)
                    categoryName = "Uncategorized";
                else
                    categoryName = category.imekategorije;
            }

            ViewBag.skola = schoolName;
            ViewBag.category = categoryName;
            ViewBag.level = level;
            return View(findKurs);
        }
    }
}

Controllers/LearningController.cs
using eLearning.Interfaces;
using eLearning.Models;
using eLearning.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using eLearning.Services;

namespace eLearning.Controllers
{
    public class LearningController : Controller
    {
        // instanciranje servisa (svih funkcija koje su navedene u IKorisnikServices i implementirane u KorisnikServices) za kontrolu korisnika
        private readonly IKorisnikServices _korisnikServices;

        public LearningController(IKorisnikServices korisnikServices)
        {
            _korisnikServices = korisnikServices;
        }

        // Pocetna stranica
        public IActionResult Index()
        {
            return View();
        }
        // Profil stranica
        [HttpGet]
        public IActionResult Profile()
        {
            if (User.Identity.IsAuthenticated)
            {
                string Id = HttpContext.User.Claims.First(c => c.Type == "KorisnikID").Value;
                Korisnik korisnik = _korisnikServices.FindUserById(Id);
                ViewBag.korisnik = korisnik;

                return View();
            }
            return RedirectToAction("Index");
        }
        // Promena password-a na profil stranici
        [HttpPost]
        public IActionResult ChangePassword(KorisnikProfileViewModel korisnik)
        {
            if (User.Identity.IsAuthenticated)
            {
                string Id = HttpContext.User.Claims.First(c => c.Type == "KorisnikID").Value;
                Korisnik k = new()
                {
                    password = Security.Hash256(korisnik.password),
                };
                _korisnikServices.UpdateUserPassword(Id, k);
                Logout();
            }
            return RedirectToAction("Profile");
        }

        // Login stranica
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult Login(KorisnikLoginViewModel korisnikVM)
        {
            if (!ModelState.IsValid)
                return View(korisnikVM);

            Korisnik korisnik = _korisnikServices.Find(korisnikVM.korisnickoIme);

            if (korisnik == null || korisnik.password != Security.Hash256(korisnikVM.password))
            {
                // poruka o neuspesnoj prijavi
                ModelState.AddModelError(string.Empty, "Invalid login attempt");
                return View(korisnikVM);
            }

            string role = "Korisnik";
            if (korisnik.tip == 2)
                role = "Admin";

            List<Claim> userClaims = new()
            {
                new Claim("KorisnikID", korisnik.userID),
                new Claim("username", korisnik.korisnickoIme),
                new Claim("email", korisnik.email),
                new Claim(ClaimTypes.Role, role),
            };

            var userIdentity = new ClaimsIdentity(userClaims, "User Identity");
            var userPrincipal = new ClaimsPrincipal(new[] { userIdentity });

            HttpContext.SignInAsync(userPrincipal, new AuthenticationProperties
            {
                IsPersistent = korisnikVM.remember,
                ExpiresUtc = DateTime.Now.AddHours(1)
            });

            // dodavanje auth cookie
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult Register(KorisnikRegViewModel korisnikVM)
        {
            if (!ModelState.IsValid)
                return View(korisnikVM);

            // provera da li je korisnik vec registrovan
            Korisnik stariKorisnik = _korisnikServices.Find(korisnikVM.korisnickoIme);
            if (stariKorisnik != null)
            {
                ModelState.AddModelError(string.Empty, $"Username \"{korisnikVM.korisnickoIme}\" is already taken.");
                return View();
            }

            Korisnik k = new()
            {
                korisnickoIme = korisnikVM.korisnickoIme,
                email = korisnikVM.email,
                password = Security.Hash256(korisnikVM.password),
                tip = 1
            };
            _korisnikServices.Insert(k);
            return RedirectToAction("Index");
        }
    }
}

Controllers/SchoolsController.cs
using eLearning.Interfaces;
using eLearning.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eLearning.Controllers
{
    public class SchoolsController : Controller
    {
        private readonly ISchoolServices _schoolServices;
        private readonly IKurseviServices _kurseviServices;

        public SchoolsController(ISchoolServices schoolServices, IKurseviServices kurseviServices)
        {
            _schoolServices = schoolServices;
            _kurseviServices = kurseviServices;
        }

        [HttpGet]
        public IActionResult Index(string name, int? page)
        {
            List<Skola> skole;
            // prosledjivanje name parametra za pretragu u View radi njegovog pamcenja u formi. 
            ViewBag.name = name;

            // dodeljivanje podrazumevanih vrednosi ako su parametri null
            if (page == null) page = 1;
            int pageSize = 8;

            // popunjavanje liste sa skolama i popunjavanje promenjive za cuvanje ukupnog broja skola prema zadatim parametrima
            int schoolCount;
            (skole, schoolCount) = _schoolServices.GetSchools(name, (int)page, pageSize);

            // odredjivanje maksimalnog broja stranica
            double maxPages = schoolCount / (double)pageSize;
            maxPages = Math.Ceiling(maxPages);

            // prosledjivanje u View zbog generisanja menija sa stranicama
            ViewBag.page = page;
            ViewBag.maxPages = maxPages;

            return View(skole);
        }

        // Metoda koja vraca parcijalni view za ispis kurseva prema skoli
        [HttpPost]
        public IActionResult SchoolCourses(string schoolID)
        {
            List<Kursevi> courses = _kurseviServices.FindBySchool(schoolID);
            ViewBag.skola = _schoolServices.Find(schoolID);
            return PartialView("_SchoolCourses", courses);
        }
    }
}

Views/Learning/Index.cshtml
@{
    ViewBag.Title = "E-learning";
}

<section class="main">
    <div class="main-left">
        <h1>The Best Free <br> Online Courses</h1>

        @if (User.Identity.IsAuthenticated)
        {
            <div class="btn-wrap">
                <div class="btn"><a asp-controller="Kursevi" asp-action="Courses">Courses</a></div>
                <div class="btn btn-white"><a asp-controller="Schools" asp-action="Index">Schools</a></div>
            </div>
        }
        else
        {
            <h2>Sign in to see the content we offer</h2>
            <div class="outer-circle">
                <div class="inner-circle">
                </div>
            </div>
        }
        <br/>
    </div>
    <div class="main-right">
        <img class="img1" src="images/Sajt-slike/slika2.png" alt="">
    </div>
</section>

Views/Learning/Login.cshtml
@model KorisnikLoginViewModel
@{ ViewBag.Title = "E-learning"; }

@section skripte{
    <link rel="stylesheet" href="~/css/login.css">
}
<div class="reg-wrap">
    <div class="login-wrap">
        <div class="login">
            <h1>Login</h1>
            <div asp-validation-summary="ModelOnly" class="error"></div>
            <form asp-controller="Learning" asp-action="Login" method="post">
                <label>Username</label>
                <input asp-for="korisnickoIme" />
                <span asp-validation-for="korisnickoIme"></span>
                <label>Password</label>
                <input asp-for="password" />
                <span asp-validation-for="password"></span>
                <label><input asp-for="remember"> Remember me</label>
                <input class="signInBtn" type="submit" value="Sign In" />
            </form>
            <a asp-controller="Learning" asp-action="Register">Don't have an account?</a>
        </div>
    </div>
</div>

Views/Learning/Profile.cshtml
@model KorisnikProfileViewModel


@{ ViewBag.Title = "E-learning"; }
@section skripte{
    <link rel="stylesheet" href="~/css/profile.css">
}

<h1>Your profile</h1>
<div class="profile">
    <form asp-controller="Learning" asp-action="ChangePassword" method="post">
        <div class="profile-input">
            <label>User name</label>
            <input name="username" type="text" value="@User.Claims.First(c => c.Type == "username").Value" disabled/>
        </div>
        <div class="profile-input">
            <label>User email</label>
            <input name="email" type="text" value="@User.Claims.First(c => c.Type == "email").Value" disabled/>
        </div>
        <div class="profile-input">
            <label asp-for="password"></label>
            <input asp-for="password" />
            <span asp-validation-for="password"></span>
        </div>
        <div class="profile-input">
            <label asp-for="confirmPassword"></label>
            <input asp-for="confirmPassword" />
            <span asp-validation-for="confirmPassword"></span>
        </div>
        <button type="submit">Change password</button>
    </form>
</div>

Views/Learning/Register.cshtml
@model KorisnikRegViewModel

@{ ViewBag.Title = "E-learning"; }
@section skripte{
    <link rel="stylesheet" href="~/css/login.css">
    <link rel="stylesheet" href="~/css/register.css">
}

<div class="reg-wrap">
    <div class="login-wrap">
        <div class="login">
            <h1>Register</h1>
            <div asp-validation-summary="ModelOnly" class="error"></div>
            <form asp-controller="Learning" asp-action="Register" method="post">
                <label asp-for="korisnickoIme"></label>
                <input asp-for="korisnickoIme" />
                <span asp-validation-for="korisnickoIme"></span>

                <label asp-for="email"></label>
                <input asp-for="email" />
                <span asp-validation-for="email"></span>

                <label asp-for="password"></label>
                <input asp-for="password" />
                <span asp-validation-for="password"></span>

                <label asp-for="confirmPassword"></label>
                <input asp-for="confirmPassword" />
                <span asp-validation-for="confirmPassword"></span>

                <input class="signInBtn" type="submit" value="Sign Up" />
            </form>
            <a asp-controller="Learning" asp-action="Login">Already have an account?</a>
        </div>
    </div>
</div>